# Generated by Django 3.0.4 on 2020-03-19 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0043_auto_20200319_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetaccessrequest',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 12, 55, 22, 798957)),
        ),
    ]
